package api

//type GetLogonqq struct {
//	Ret string `json:"ret"`
//}
//
//type QQList struct {
//}
//
//type AutoGenerated struct {
//	NAMING_FAILED string `json:"昵称"`
//	NAMING_FAILED string `json:"登录状态"`
//	NAMING_FAILED string `json:"等级信息"`
//	NAMING_FAILED string `json:"收发信息"`
//	IP            string `json:"登录IP"`
//	NAMING_FAILED string `json:"登录协议"`
//	NAMING_FAILED string `json:"腾讯服务器"`
//}
//
//func Getlogonqq() (){
//	data, err := Net.Post(app_conf.Http_Api+"/getlogonqq", nil, nil, nil, nil)
//	if err != nil {
//		return false, err
//	}
//	var ret LoginqqRet
//	jsr := jsoniter.ConfigCompatibleWithStandardLibrary
//	err = jsr.UnmarshalFromString(data, &ret)
//	if err != nil {
//		return false, err
//	}
//	if ret.Ret == "true" {
//		return true, nil
//	} else {
//		return false, nil
//	}
//}
